// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqUKBEB5WTvg2lc-p1rAr0m8hYIm2mlGI',
    appId: '1:743092267589:web:f3755bcc60500753c6d12c',
    messagingSenderId: '743092267589',
    projectId: 'studenthub-40801',
    authDomain: 'studenthub-40801.firebaseapp.com',
    databaseURL: 'https://studenthub-40801-default-rtdb.firebaseio.com',
    storageBucket: 'studenthub-40801.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9hshYcpZPdfvMbxBGOohTqEFQsFzyed4',
    appId: '1:743092267589:android:cbb609b63373babcc6d12c',
    messagingSenderId: '743092267589',
    projectId: 'studenthub-40801',
    databaseURL: 'https://studenthub-40801-default-rtdb.firebaseio.com',
    storageBucket: 'studenthub-40801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWb9hCChLS9P16K5vOu616Z0BrXH5ZPV8',
    appId: '1:743092267589:ios:6376f5b953561772c6d12c',
    messagingSenderId: '743092267589',
    projectId: 'studenthub-40801',
    databaseURL: 'https://studenthub-40801-default-rtdb.firebaseio.com',
    storageBucket: 'studenthub-40801.appspot.com',
    iosBundleId: 'com.example.studentProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWb9hCChLS9P16K5vOu616Z0BrXH5ZPV8',
    appId: '1:743092267589:ios:eb4a9ca18c3170a4c6d12c',
    messagingSenderId: '743092267589',
    projectId: 'studenthub-40801',
    databaseURL: 'https://studenthub-40801-default-rtdb.firebaseio.com',
    storageBucket: 'studenthub-40801.appspot.com',
    iosBundleId: 'com.example.studentProfile.RunnerTests',
  );
}
